### ISSUE TITLE
Parameter missing from the documentation. Study Subjects Endpoint

### ISSUE THREAD

**Issue by syedwaleedhyder** [actigraph/CentrePoint3APIDocumentation#15]
I have noticed a difference in the documentation and the actual response of the API for study subjects.

The discrepancy is found on the following link.
https://github.com/actigraph/CentrePoint3APIDocumentation/blob/main/sections/subjects.md

### Request
```http
GET /centrepoint/v3/Studies/{studyId}/Subjects
```
There is no mention of the parameter "assignmentId" in the response documentation. But when I actually call the endpoint, I receive this parameter. As shown in the image below
![image](https://user-images.githubusercontent.com/22868291/117501281-448dd380-af97-11eb-8237-eca56f0aeed3.png)

I can provide more details if required.

**Comment by wscott3** [comment]
Thank you for pointing this out. It has been fixed.
